language: java
sudo: required
services:
  - mysql
jdk:
- oraclejdk8
env:
  matrix:
    fast_finish: true
    - SERV=lucee4 DB=mysql
before_install:
  # Get Commandbox
- sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
- sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
  /etc/apt/sources.list.d/commandbox.list
install:
  # Install Commandbox
- sudo apt-get update && sudo apt-get --assume-yes install commandbox
  # Install Wheels CLI
- box install cfwheels-cli
before_script:before_install:
  # Create databases
- mysql -e 'CREATE DATABASE wheelstestdb;'
- box cp 'src/cb/$SERV_$DB.cfm '`server info property=serverHomeDirectory`/WEB-INF/lucee-web/lucee-web.xml.cfm'"
  # Start The Server
- box server start $SERV app.webxml='src/cb/$SERV_$DB.xml.cfm'
  # Basically, we now run the wheels CLI test runner, pointing it to the current server
script: >
  testResults="$(box wheels test core $SERV )";
  echo "$testResults";
  if ! grep -i "\Tests Complete: All Good!" <<< $testResults;  then exit 1; fi
notifications:
    email: false
