language: java
sudo: required
services:
  - mysql
jdk:
- oraclejdk8
env:
  matrix:
    - SERV=lucee4 CONFIG=src/cb/mysql.json
before_install:
  # Get Commandbox
- sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
- sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
  /etc/apt/sources.list.d/commandbox.list
install:
  # Install Commandbox
- sudo apt-get update && sudo apt-get --assume-yes install commandbox
  # Install Wheels CLI
- box install cfwheels-cli
  # Install CFConfig
- box install commandbox-cfconfig
before_script:
  # Create databases
- mysql -e 'CREATE DATABASE wheelstestdb;'
  # Start The Server
- box server start $SERV
  # Add the datasource via CFConfig
- box cfconfig import from=$CONFIG
  # Basically, we now run the wheels CLI test runner, pointing it to the current server
script: >
  testResults="$(box wheels test core $SERV )";
  echo "$testResults";
  if ! grep -i "\Tests Complete: All Good!" <<< $testResults;  then exit 1; fi
notifications:
    email: false
