language: java
sudo: required
services:
  - mysql
  - postgresql
jdk:
  - oraclejdk8
env:
  matrix:
    # Works
    #- CFENGINE=lucee@4.5.5+006 DB=H2 MODE=MySQL DBCLASS=org.h2.Driver
    # Works
    #- CFENGINE=lucee@4.5.5+006 DB=H2 MODE=PostgreSQL DBCLASS=org.h2.Driver
    # Works
    #- CFENGINE=lucee@4.5.5+006 DB=H2 MODE=Oracle DBCLASS=org.h2.Driver
    # Works
    #- CFENGINE=lucee@4.5.5+006 DB=H2 MODE=MSSQLServer DBCLASS=org.h2.Driver
    # Works
    #- CFENGINE=lucee@5.1.2+24  DB=MySQL DBCLASS=org.gjt.mm.mysql.Driver
    # Test
    - CFENGINE=lucee@4.5.5+006 DB=PostgreSQL DBCLASS=org.postgresql.Driver
    - CFENGINE=lucee@5.1.2+24  DB=PostgreSQL DBCLASS=org.postgresql.Driver

    #- CFENGINE=adobe@11.0.11+301867 DB=MySQL HOST=127.0.0.1 USERNAME=root DBCLASS=com.mysql.jdbc.Driver
    #- CFENGINE=adobe@11 DB=PostgreSql PORT=5432 user=postgres DBCLASS=org.postgresql.Driver
    #- CFENGINE=adobe@2016 DB=MySQL PORT=3306 user=root DBCLASS=org.gjt.mm.mysql.Driver
    #- CFENGINE=adobe@2016 DB=PostgreSql PORT=5432 user=postgres DBCLASS=org.postgresql.Driver
before_install:
  # Get Commandbox
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install:
  # Install Commandbox
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  # Install Wheels CLI
  - box version
  - box install cfwheels-cli
  # Install CFConfig
  - box install commandbox-cfconfig
before_script:
  # Create databases
  - if [[ "$DB" == "MySQL" ]]; then mysql -e 'CREATE DATABASE wheelstestdb;'; fi
  - if [[ "$DB" == "PostgreSQL" ]]; then psql -c 'create database wheelstestdb;' -U postgres; fi
  # Start The Server
  - box server start cfengine=$CFENGINE
  # Add the datasource via CFConfig
  - if [[ "$DB" == "H2" ]]; then box cfconfig datasource save name=wheelstestdb database=wheelstestdb dbdriver=$DB class="$DBCLASS" custom="mode=$MODE&path=./db/"  dsn="jdbc:h2:{path}{database};MODE={mode}" allow=511 clob=true blob=true; fi
  - if [[ "$DB" == "MySQL" ]]; then box cfconfig datasource save name=wheelstestdb database=wheelstestdb dbdriver=$DB class="$DBCLASS" host=127.0.0.1 port=3306 username=travis password="" blob=true clob=true; fi
  - if [[ "$DB" == "PostgreSQL" ]]; then box cfconfig datasource save name=wheelstestdb database=wheelstestdb dbdriver=$DB class="$DBCLASS" host=127.0.0.1 port=5432 username=postgres password="" blob=true clob=true; fi
  # Disable sitewide error handler for ACF
  #- if [[ "$CFENGINE" == "adobe@11" ]]; then box cfconfig set generalErrorTemplate=""; fi
  # Restart The Server
  - box server restart
  # Basically, we now run the wheels CLI test runner, pointing it to the current server
  - box cfconfig datasource list
script: >
  testResults="$(box wheels test type=core servername=cfwheels adapter=$MODE )";
  echo "$testResults";
  if ! grep -i "\Tests Complete: All Good!" <<< $testResults;  then exit 1; fi
notifications:
    email: false
