language: java
sudo: required
services:
  - mysql
  - postgresql
jdk:
  - oraclejdk8
env:
  matrix:
    - CFENGINE=lucee@4 DBDRIVER=MySQL HOST=127.0.0.1 PORT=3306 user=root DBCLASS=org.gjt.mm.mysql.Driver
    - CFENGINE=lucee@4 DBDRIVER=PostgreSql HOST=127.0.0.1 PORT=5432 user=postgres DBCLASS=org.postgresql.Driver
    - CFENGINE=lucee@5 DBDRIVER=MySQL HOST=127.0.0.1 PORT=3306 user=root DBCLASS=org.gjt.mm.mysql.Driver
    - CFENGINE=lucee@5 DBDRIVER=PostgreSql HOST=127.0.0.1 PORT=5432 user=postgres DBCLASS=org.postgresql.Driver
    - CFENGINE=adobe@11 DBDRIVER=MySQL HOST=127.0.0.1 PORT=3306 user=root DBCLASS=org.gjt.mm.mysql.Driver
    - CFENGINE=adobe@11 DBDRIVER=PostgreSql HOST=127.0.0.1 PORT=5432 user=postgres DBCLASS=org.postgresql.Driver
    - CFENGINE=adobe@2016 DBDRIVER=MySQL HOST=127.0.0.1 PORT=3306 user=root DBCLASS=org.gjt.mm.mysql.Driver
    - CFENGINE=adobe@2016 DBDRIVER=PostgreSql HOST=127.0.0.1 PORT=5432 user=postgres DBCLASS=org.postgresql.Driver
before_install:
  # Get Commandbox
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install:
  # Install Commandbox
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  # Install Wheels CLI
  - box version
  - box install cfwheels-cli
  # Install CFConfig
  - box install commandbox-cfconfig
before_script:
  # Create databases
  - mysql -e 'CREATE DATABASE wheelstestdb;'
  - psql -c 'create database wheelstestdb;' -U postgres
  # Start The Server
  - box server start cfengine=$CFENGINE
  # Add the datasource via CFConfig
  - box cfconfig datasource save name=wheelstestdb database=wheelstestdb dbdriver=$DBDRIVER class=$DBCLASS port=$PORT host=$HOST username=$USER blob=true clob=true
  # REStart The Server
  - box server restart
  # Basically, we now run the wheels CLI test runner, pointing it to the current server
  - box cfconfig datasource list
script: >
  testResults="$(box wheels test core cfwheels )";
  echo "$testResults";
  if ! grep -i "\Tests Complete: All Good!" <<< $testResults;  then exit 1; fi
notifications:
    email: false
